http:
  routers:
    Router-1:
      rule: "Host(`*`)"
      service: service-id
      # will terminate the TLS request
      tls:
        options: myTLSOptions
        passthrough: true
tls:
  certificates:
    - certFile: ./certs/traefik.crt
      keyFile: ./certs/traefik.key
      stores:
        - default
    - certFile: ./certs/traefik.crt
      keyFile: ./certs/traefik.key
  options:
    myTLSOptions:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
